### ISSUE TITLE
关于贵站 logo

### ISSUE THREAD

**Issue by nnnnw** [imgradeone/wikimimo#10]
请问贵站的 `https://www.wikimimo.com/logo.svg` 、`https://www.wikimimo.com/archive-button.svg` 等图标是如何制作的，谢谢

**Comment by imgradeone** [comment]
不建议您在 Issue 中提出此类问题。如有需要，您可以通过邮箱 imgradeone@outlook.com 与我探讨。该 Issue 将被关闭。

**Comment by imgradeone** [comment]
什么啊，直接删号了？

**Comment by imgradeone** [comment]
告诉你吧，是 Figma。  
想骂我“够罕见”的现在可以开始了。
